name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      # Add any environment variables needed to run baton-tenable-vm
      BATON_ACCESS_KEY: ${{ secrets.BATON_ACCESS_KEY }}
      BATON_SECRET_KEY: ${{ secrets.BATON_SECRET_KEY }}
      BATON_CONNECTOR_FLAGS: >-
        --access-key ${BATON_ACCESS_KEY} 
        --secret-key ${BATON_SECRET_KEY}
      # The following parameters are passed to grant/revoke commands
      # Change these to the correct IDs for your test data
      CONNECTOR_GRANT: 'group:1149063:member:user:2430947'
      CONNECTOR_ENTITLEMENT: 'group:1149063:member'
      CONNECTOR_PRINCIPAL: '2430947'
      CONNECTOR_PRINCIPAL_TYPE: 'user'
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-tenable-vm
        run: go build ./cmd/baton-tenable-vm
      - name: Run baton-tenable-vm
        run: ./baton-tenable-vm ${{ env.BATON_CONNECTOR_FLAGS }}

      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin

      - name: Check for grant before revoking

        run:
          baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status ".grants[].principal.id.resource == \"${{ env.CONNECTOR_PRINCIPAL }}\"" | grep true


      - name: Revoke grants
        run: ./baton-tenable-vm ${{ env.BATON_CONNECTOR_FLAGS }}  --revoke-grant="${{ env.CONNECTOR_GRANT }}"

      - name: Check grant was revoked
        run: ./baton-tenable-vm ${{ env.BATON_CONNECTOR_FLAGS }} && baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status "if .grants then .grants[]?.principal.id.resource != \"${{ env.CONNECTOR_PRINCIPAL }}\" else . end"

      - name: Grant entitlement
        run: ./baton-tenable-vm ${{ env.BATON_CONNECTOR_FLAGS }} --grant-entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --grant-principal="${{ env.CONNECTOR_PRINCIPAL }}" --grant-principal-type="${{ env.CONNECTOR_PRINCIPAL_TYPE }}"

      - name: Check grant was re-granted

        run:
          ./baton-tenable-vm ${{ env.BATON_CONNECTOR_FLAGS }} && baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status ".grants[].principal.id.resource == \"${{ env.CONNECTOR_PRINCIPAL }}\"" | grep true
